const path = {
    ADMIN: "/administrator",
    ORDER: "/administrator/sales/orders",
    CREATE_ORDER: "/administrator/sales/orders/create-order",
    PACKAGE: "/administrator/sales/packages",
    NEWS: "/administrator/news",
    COMBO: "/administrator/sales/combos",
    LIST_COMMISSION: "/administrator/commission",
    SETTING_LEVEL_COMMISSION: "/administrator/setting-level-commission",
    COMMISSION_PACKAGE: "/administrator/setting-commission/package",
    COMMISSION_COMBO: "/administrator/setting-commission/combo",
    CATE_PACKAGE: "/administrator/sales/cate-packages",
    AGENCY: "/administrator/agency",
    ROLE: "/administrator/role",
    EXCHANGE_CURRENCY: "/administrator/exchange-currency",
    PROMOTION: "/administrator/promotion",
    REFERAL: "/administrator/referal",
    GROUP_PERMISSION: "/administrator/group-permission",
    CUSTOMER: "/administrator/customer",
    USER: "/administrator/user-manage",
    SETTING_PAYMENT: "/administrator/setting/payment",
    SETTING_SYSTEM: "/administrator/setting/system",
    SALE_REPORT: "/administrator/sale-report",
    PAYMENT_REPORT: "/administrator/payment-report",
    COMMISSION_REPORT: "/administrator/commission-report",
    WITHDRAW_REPORT: "/administrator/withdraw-report",
    PARTNER_REPORT: "/administrator/partner-report",
    PACKAGE_REPORT: "/administrator/package-report",
    RECEIPT: "/administrator/receipt",
}
export default path;